export class PageConstants {

  static readonly DELAY_TIME: number = 2000;

  static readonly BUTTON_SPACE: string = '6vp';

  static readonly  MAIN_PAGE_URL: string = 'pages/MainPage';

  static readonly HOME_INDEX: number = 0;

  static readonly GLOBE_INDEX: number = 1;

  static readonly WEALTH_INDEX: number = 2;

  static readonly INTERESTS_INDEX: number = 3;

  static readonly MY_INDEX: number = 4;

  static readonly IMAGE_ASPECT_RATIO: number = 1;
}