export class StyleConstants {

  static readonly FULL_WIDTH: string = '100%';

  static readonly FULL_HEIGHT: string = '100%';

  static readonly SEVENTY_HEIGHT: string = '70%';

  static readonly SIXTY_HEIGHT: string = '60%';

  static readonly SIXTY_WIDTH: string = '60%';

  static readonly FIFTY_HEIGHT: string = '50%';

  static readonly HUNDRED_FIFTEEN_WIDTH: string = '115%';

  static readonly FOUR_SPACE: string = '4vp';

  static readonly TWELVE_SPACE: string = '12vp';

  static readonly ITEM_SPACE: string = '14vp';

  static readonly FIFTEEN_SPACE: string = '15vp';

  static readonly FONT_WEIGHT_SEVEN: number = 700;

  static readonly FONT_WEIGHT_FIVE: number = 500;

  static readonly FONT_WEIGHT_FOUR: number = 400;

  static readonly TWO_TEXT_LINE: number = 2;

  static readonly FULL_OPACITY: number = 1;

  static readonly SIXTY_OPACITY: number = 0.6;

  static readonly EIGHTY_OPACITY: number = 0.8;

  static readonly LAYOUT_WEIGHT: number = 1;

  static readonly FLEX_BASIC: number = 1;

  static readonly FLEX_SHRINK: number = 1;

  static readonly FLEX_GROW: number = 1;

  static readonly DISPLAY_ONE: number = 1;

  static readonly DISPLAY_TWO: number = 2;

  static readonly DISPLAY_THREE: number = 3;

  static readonly DISPLAY_FOUR: number = 4;

  static readonly IMAGE_ASPECT_RATIO: number = 2.25;

  static readonly HALF_ONE: number = 0.5;

  static readonly MINUS_ONE: number = -1;
}